Repository googleapis/python-dialogflow, pull requests merged in 2020-05, with the labels that each got.

#188 chore: corrects repository URL
  noxfile.py
  setup.py
Labels: automerge, cla: yes, kokoro:force-run

#189 feat: release_status to production/stable
  .repo-metadata.json
  README.rst
  setup.py
Labels: automerge, cla: yes

#195 chore: adds description, long_description
  setup.py
Labels: cla: yes

#196 chore: add synth.py to list of ignores
  synth.py
Labels: cla: yes

#155 docs: move to googleapisdotdev
  .readthedocs.yml
  README.rst
Labels: automerge, cla: yes
