Repository googleapis/python-dialogflow, pull requests merged in 2021-04, with the labels that each got.

#273 fix: remove unused proto InputText, InputAudio
  google/cloud/dialogflow_v2/__init__.py
  google/cloud/dialogflow_v2beta1/__init__.py
  google/cloud/dialogflow_v2beta1/proto/participant.proto
  google/cloud/dialogflow_v2beta1/types/__init__.py
  google/cloud/dialogflow_v2beta1/types/participant.py
  synth.metadata
Labels: api: dialogflow, cla: yes, context: partial

#277 chore: prevent normalization of semver versioning
  setup.py
Labels: api: dialogflow, cla: yes

#279 chore(revert): revert preventing normalization
  setup.py
Labels: api: dialogflow, automerge, cla: yes
