Repository googleapis/python-dialogflow, pull requests merged in 2021-09, with the labels that each got.

#388 test(samples): replace the deleted gcs file with public file
  samples/snippets/participant_management_test.py
Labels: cla: yes, api: dialogflow

#382 docs(samples): add region tags to update intent sample
  samples/snippets/update_intent.py
Labels: cla: yes, api: dialogflow, samples

#390 test(samples): replace the deleted gcs file with gcs file located in cloud-samples-data
  samples/snippets/participant_management_test.py
Labels: cla: yes, api: dialogflow, samples

#370 docs(samples): add set agent code sample
  samples/snippets/set_agent.py
  samples/snippets/set_agent_test.py
Labels: cla: yes, api: dialogflow, samples

#391 chore: revert owlbot main branch templates
  owlbot.py
Labels: cla: yes, api: dialogflow, automerge

#397 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: dialogflow, automerge

#400 ci: fix flaky test
  samples/snippets/participant_management.py
Labels: cla: yes, api: dialogflow

#402 ci: increase create_participant timeout to 600
  samples/snippets/participant_management.py
Labels: cla: yes, api: dialogflow

#401 docs(samples): added webhook code snippet
  samples/snippets/requirements.txt
  samples/snippets/webhook.py
  samples/snippets/webhook_test.py
Labels: cla: yes, api: dialogflow, samples
