Repository googleapis/python-dialogflow, pull requests merged in 2021-08, with the labels that each got.

#356 chore: require CODEOWNER review and up to date branches
  .github/sync-repo-settings.yaml
Labels: api: dialogflow, cla: yes

#357 docs(samples): add update intent code sample
  samples/snippets/update_intent.py
  samples/snippets/update_intent_test.py
Labels: cla: yes, api: dialogflow, samples

#368 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: cla: yes, api: dialogflow, automerge, samples

#372 chore: migrate to main branch
  .github/sync-repo-settings.yaml
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CHANGELOG.md
  CONTRIBUTING.rst
  README.rst
  UPGRADING.md
  docs/conf.py
  owlbot.py
  samples/snippets/noxfile.py
Labels: cla: yes, api: dialogflow
